### ISSUE TITLE
Prepare Release

### ISSUE THREAD

**Issue by artalat** [BlueBaseJS/cli#47]
Prepare the is repo for the final release of V1.

- [x] Configure CI/CD pipeline (#74)
- [x] Configure Semantic Releases (#74)
- [x] Make sure all PR status checks are passing (#74)
- [x] Update main README file, with proper info
- [x] Verify all packages have proper README files
- [x] Remove forked status on GitHub [DONE]
